# Generated by Django 4.2.4 on 2023-08-31 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("link_profiles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="links",
            new_name="profile",
        ),
    ]
